environment:
  COVERALLS_REPO_TOKEN:
    secure: tEJ3Pi//WIBJgjtg3dFXClJxZ0kX9Aak/B3XRMal/uCTfjb0ayWf2rwbrB4jpUUu
version: 0.0.{build}
configuration: Release
assembly_info:
  patch: true
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
before_build:
  - nuget restore
build:
  publish_nuget: true
  verbosity: minimal
after_test:
- cmd: .\coverage.cmd
before_package:
- ps: >-
    $version = If ( $env:APPVEYOR_BUILD_VERSION == "master" ) {"$env:APPVEYOR_BUILD_VERSION"} Else {"$env:APPVEYOR_BUILD_VERSION-alpha"}
    (Get-Content "$env:APPVEYOR_BUILD_FOLDER\src\SilverRock.AzureTools\SilverRock.AzureTools.nuspec") `
        -replace '<version>[^<]*?</version>', ('<version>{0}</version>' -f $env:APPVEYOR_BUILD_VERSION) |
      Out-File "$env:APPVEYOR_BUILD_FOLDER\src\SilverRock.AzureTools\SilverRock.AzureTools.nuspec"